extensive_philosopher_list = (
    'Socrates',
    'Plato',
    'Aristotle',
    'Carneades',
    'Jesus Christ',
    'Epictetus',
    'Marcus Aurelius',
    'Augustine',
    'Boethius',
    'Al-Kindi',
    'Avicenna',
    'Avicebron',
    'Anselm',
    'Omar Khayyam',
    'Al-Ghazali',
    'Francis of Assisi',
    'Roger Bacon',
    'Thomas Aquinas',
    'William of Ockham',
    'Niccolo Machiavelli',
    'Thomas More',
    'Michel de Montaigne',
    'Francis Bacon',
    'René Descartes',
    'Thomas Hobbes',
    'Blaise Pascal',
    'Baruch Spinoza',
    'John Locke',
    'Christian Wolff',
    'George Berkeley',
    'Julien La Mettrie',
    'Voltaire',
    'David Hume',
    'Immanuel Kant',
    'Jean-Jacques Rousseau',
    'Jeremy Bentham',
    'Friedrich Schiller',
    'Joseph de Maistre',
    'G. W. F. Hegel',
    'F. W. J. von Schelling',
    'Arthur Schopenhauer',
    'Ralph Waldo Emerson',
    'John Stuart Mill',
    'Søren Kierkegaard',
    'Henry David Thoreau',
    'Karl Marx',
    'Charles Sanders Peirce',
    'William James',
    'Friedrich Nietzsche',
    'Gottlob Frege',
    'Vilfredo Pareto',
    'George Santayana',
    'Bertrand Russell',
    'Martin Buber',
    'Martin Heidegger',
    'Ludwig Wittgenstein',
    'Karl Popper',
    'Mortimer Adler',
    'Jean-Paul Sartre',
    'Ayn Rand',
    'Hannah Arendt',
    'Simone de Beauvoir',
    'Albert Camus',
    'Jacques Maritain',
    'John Rawls',
    'Frantz Fanon',
    'Michel Foucault',
    'Bernard Williams',
    'Jacques Derrida',
    'Peter Singer',
    'Slavoj Žižek',
    'Graham Oppy',
    'Sam Harris'
)

shortened_philosopher_list = (
    'Socrates',
    'Plato',
    'Aristotle',
    'Jesus Christ',
    'Epictetus',
    'Marcus Aurelius',
    'Boethius',
    'Avicenna',
    'Roger Bacon',
    'Thomas Aquinas',
    'Niccolo Machiavelli',
    'Francis Bacon',
    'René Descartes',
    'Thomas Hobbes',
    'Blaise Pascal',
    'Baruch Spinoza',
    'John Locke',
    'Voltaire',
    'David Hume',
    'Immanuel Kant',
    'Jean-Jacques Rousseau',
    'Arthur Schopenhauer',
    'John Stuart Mill',
    'Søren Kierkegaard',
    'William James',
    'Friedrich Nietzsche',
    'Bertrand Russell',
    'Martin Heidegger',
    'Ludwig Wittgenstein',
    'Jean-Paul Sartre',
    'Ayn Rand',
    'Hannah Arendt',
    'Albert Camus',
    'Peter Singer',
    'Slavoj Žižek'
)
